### ISSUE TITLE
Getting `no match`...

### ISSUE THREAD

**Issue by elifarley** [thimc/ed#1]
Hi! Tack a lot for creating this `ed` clone. I need to include this in a code processing runtime ([CEDARScript](https://github.com/CEDARScript/cedarscript-integration-aider)), but I could not get it to work.

Could you help me, please?

Here's the file that needs editing:

```1.py
class BaseConverter:
    def encode(self, i):
        neg, value = self.convert(i, self.decimal_digits, self.digits, "-")
    def decode(self, s):
        neg, value = self.convert(s, self.digits, self.decimal_digits, self.sign)
def convert(self, number, from_digits, to_digits, sign):
```

And here's the file with the editing script:
```script.ed
H
/def convert/s/self, //
/self.convert/s/self\.(convert)/\1/g
w
q
```

And this is the sequence of commands I tried:

```shell
ed 1.py < script.ed
287
script, line 2: no match
script, line 2: no match
286
```

Now, if I use `ed` that comes in MacOS X, I get a different error:
```
286
?
script, line 3: no match
```

Do you have any idea of what's wrong here?

Thank you!

**Comment by elifarley** [comment]
If I use an address range, it works:
```ed
,/def convert/s/self, //
```

But I need to perform the replacements only on each line that matches `/def convert/`

**Comment by elifarley** [comment]
The correct syntax is:

```
H
g/def convert/s/self, //
g/self\.convert/s/self\.\(convert\)/\1/g
w
q
```

Standard `ed` performs the changes as expected and outputs:

```
286
270
```

Your ed command doesn't change anything and then outputs:

```
287
def convert(self, number, from_digits, to_digits, sign):
        neg, value = self.convert(i, self.decimal_digits, self.digits, "-")
        neg, value = self.convert(s, self.digits, self.decimal_digits, self.sign)
286
```

**Comment by thimc** [comment]
Hi, thanks for the feedback. I will look in to it, I am quite surprised that the tests aren't failing for the global command but I guess there are edge cases.

**Comment by thimc** [comment]
Hi, thanks for the feedback. I will look in to it, I am quite surprised that the tests aren't failing for the global command but I guess there are edge cases.

EDIT:

Actually the correct syntax is:
```
H
g/def convert/s/self, //
g/self\.convert/s/self\.(convert)/\1/g
w
q
```

Escaping the parentheses is not needed in RE2, but I am aware that the substitute command isn't working as expected.

**Comment by knieriem** [comment]
Hi, when using a command sequence like `g/pattern/ s/a/b/` I observed a behaviour
similar to the one described in this issue. It appears to be caused partly by the way line indices get calculated within Editor.substitute(). With the changes linked above I get the following output:

```python
class BaseConverter:
    def encode(self, i):
        neg, value = convert(i, self.decimal_digits, self.digits, "-")
    def decode(self, s):
        neg, value = convert(s, self.digits, self.decimal_digits, self.sign)
def convert(number, from_digits, to_digits, sign):
```
This appears to be the same what standard `ed` does.

One of the patches addresses the extra output of the matched lines.

**Comment by thimc** [comment]
> Hi, when using a command sequence like `g/pattern/ s/a/b/` I observed a behaviour similar to the one described in this issue. It appears to be caused partly by the way line indices get calculated within Editor.substitute(). With the changes linked above I get the following output:
> ....
> One of the patches addresses the extra output of the matched lines.

Hi, I can't thank you enough, I have been meaning to get around to this. I will review the changes soon.

Would you mind creating a pull request?
